version: "3.9"

services:
  postgres:
    image: docker.io/library/postgres:15
    container_name: postgres-love
    environment:
      POSTGRES_DB: love_db
      POSTGRES_USER: love_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: